"""Protocols for domain layer interface."""

from datetime import date
from typing import Protocol


class OrderLineProtocol(Protocol):
    order_id: str
    sku: str
    qty: int


class BatchProtocol(Protocol):
    reference: str

    @property
    def _eta(self) -> date | None: ...

    def allocate(self, line: OrderLineProtocol) -> None: ...
    def deallocate(self, line: OrderLineProtocol) -> None: ...
    @property
    def allocated_quantity(self) -> int: ...
    @property
    def available_quantity(self) -> int: ...
    def can_allocate(self, line: OrderLineProtocol) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __gt__(self, other: 'BatchProtocol') -> bool: ...


class BatchRepositoryProtocol(Protocol):
    def add(self, batch: BatchProtocol) -> None: ...
    def get(self, reference: str) -> BatchProtocol: ...
